// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Contexts;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250725204902_StartPoint")]
    partial class StartPoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "C# moden bir programlama dilidir...",
                            Title = "C#'a Giriş"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Entity Framework Core, .NET için bir ORM kütüphanesidir...",
                            Title = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 3,
                            Content = "ASP.NET Core, web uygulamaları geliştirmek için kullanılan bir framework'tür...",
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Web sitelerinin temelidir, bir şablon oluşturmak için kullanılır...",
                            Title = "HTML"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Web sitelerinin görünümünü ve düzenini kontrol etmek için kullanılır...",
                            Title = "CSS"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Web sitelerine etkileşim ve dinamik özellikler eklemek için kullanılır...",
                            Title = "JavaScript"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
